### ISSUE TITLE
Make chart dependencies optional

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/helm#10]
Hi, I'd like to install your helm chart but I'd be using external services for the persistence (redis and postgres), therefore I'd prefer not to install those pods in the cluster.

With [Tags and Condition fields in dependencies](https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies) it should be easy to accomplish this behavior.

If you agree on it, I can make a PR.

Thanks!

**Comment by tarioch** [comment]
Sure, feel free to create a pr

**Comment by lyz-code** [comment]
Will probably do it throughout next week
