### ISSUE TITLE
Ability to add own ca-certificate

### ISSUE THREAD

**Issue by mosesdd** [WeblateOrg/helm#101]
Hi,

if you use a self hosted GitLab instance for example, you need to add the ca-certificate for communication over https.
Yet there is no possibility to add this via the values for this chart. I need to patch the deployment afterwards to mount the ca-certificate inside the Weblate container as a secret:

`kubectl patch deployment weblate -n weblate --type='json' -p='[{"op": "add", "path": "/spec/template/spec/volumes/0", "value":  {"name": "own-ca-certificate", "secret": {"secretName": "own-ca-certificate"}}}]'`

`kubectl patch deployment weblate -n weblate --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/volumeMounts/0", "value": {"mountPath": "/etc/ssl/certs/own-ca-certificate.pem", "subPath": "own-ca-certificate.pem", "name": "own-ca-certificate"}}]'`

It would be nice if it would be possible to create a secret containing ca-certificate directly via the values.yaml

**Comment by clawoflight** [comment]
Please implement either this, or at least #161. Needing to patch a deployment after running helm for basic functionality to work is really not acceptable, and #161 would be implemented in ~8 lines of yaml :)

**Comment by nijel** [comment]
Patches are welcome 😉

**Comment by clawoflight** [comment]
@nijel Reviews & feedback are welcome ;)
