### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/helm#11]
Hi, I understand that using `helm` as the repository name for your organization makes sense. But it can lead to conflicts for the people that are forking your repository.

Something like `weblate-helm` or `weblate-chart` would solve it.

Thanks

**Comment by nijel** [comment]
The naming is consistent with other repos (for example docker or docker-compose). I understand your concern, but I'm not sure it's worth of it to rename all the repos just because this.

**Comment by lyz-code** [comment]
It makes sense, closing it then
