### ISSUE TITLE
Length of translation

### ISSUE THREAD

**Issue by raman030888** [WeblateOrg/helm#115]
Hi,

I am trying to increase the length of the translation in weblate.

I changed the environment variable as per the documentation to max-length:500
After the change I can see that English(Source Language) translation limit is 10000 now. but for all other languages its still same.

Can you please help me to increase the limit for other languages aswell.

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/user/translating.html#translated-string-length

**Comment by raman030888** [comment]
Hi Thanks for the response,

I have followed the document and set "LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH" to False.

but still the limit is shown as "310" only. could you please help

![image](https://user-images.githubusercontent.com/60535012/134323067-14767301-be84-4121-a168-26965c864318.png)

**Comment by nijel** [comment]
This is currently not exposed to Docker environment, so you have to change in settings.py (see https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization).

Also, I'm curious why you need that long translation for short source sting. Can you please share your motivation?

**Comment by raman030888** [comment]
Thanks for response..

Sometimes strings are exceeding 300..for example below one is around 402.. so I was looking for an option to modify the limit.

![image](https://user-images.githubusercontent.com/60535012/134343430-3d24390f-9d8a-423b-8557-0c0551df01c3.png)
