### ISSUE TITLE
Logs me out after adding 2 new translations

### ISSUE THREAD

**Issue by raman030888** [WeblateOrg/helm#132]
### Describe the issue

Hi Team,

When ever I tried to add new translations it logs me out after adding 2 new translations, and I need to wait for an hour, to add other translations again it logs me out.

Can you please help !!

Regards,
Raman Muthu

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

**Comment by nijel** [comment]
Do you get some error?

**Comment by raman030888** [comment]
We get the below error when it logs out..
![weblate-error](https://user-images.githubusercontent.com/60535012/149117914-81a39fec-c406-4c75-83fd-549fc49a55aa.png)

**Comment by nijel** [comment]
Can you please get the full exception for the error? See https://docs.weblate.org/en/latest/contributing/debugging.html

PS: You should upgrade, it is possible that the issue you are facing was fixed in the newer releases.

**Comment by raman030888** [comment]
Hi upgraded the weblate app to 4.8.1 and I dont see the issue with superuser.. as mentioned in the document.. 

but we have a new issue, the integration is not working with the application

do we need to change anything regards to integration? my previous app version is 4.5

**Comment by nijel** [comment]
I have no clue what kind of integration are you using and what is not working...

Also, the latest version is 4.10.1.

**Comment by raman030888** [comment]
Rest Api endpoint for /api/translations/app-20-tenant-98-global/common/en_US/file

worked on older version, on this version it is not working

**Comment by nijel** [comment]
There was no change in the API URLs. Is the full URL correct (especially look for missing/extra slashes)? Is the authentication token correct?

**Comment by raman030888** [comment]
Yes I have verified the URL aswell.. 
we are using AKS cluster and used Helm charts.. I can see the latest version in Helm chart is 4.8.1.

**Comment by raman030888** [comment]
Upgrading to Latest version helped to fix Log out issue, now with superuser , we dont see any limits for new translations
