### ISSUE TITLE
Ingress doesn't support .spec.ingressClassName

### ISSUE THREAD

**Issue by camaeel** [WeblateOrg/helm#139]
### Describe the problem

Ingress doesn't support .spec.ingressClassName field. It uses old style annotation. 
For reference: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

### Describe the solution you'd like

Support for .spec.ingressClassName field

**Comment by nijel** [comment]
Patches are welcome to fix this :-)

**Comment by camaeel** [comment]
I added PR for this issue: https://github.com/WeblateOrg/helm/pull/140
