### ISSUE TITLE
Upgrade Weblate version in the chart

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/helm#14]
Currently the chart is using weblate `4.0.4`, but when started it states:

```
INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.1.
```

I haven't dived into the documentation to see if it's straightforward, sorry :(

**Comment by tarioch** [comment]
What you normally want to do is specify `image.tag` in your values file to specify which exact docker image you want to use. They should normally be compatible with the helm chart.

**Comment by lyz-code** [comment]
I understand that, but personally it gives me more confidence if the "official chart" specifies by default the latest stable release.

If it's not in the latest, it makes me think that maybe there are some reasons unknown to me that prevented them to upgrade the image.

Anyway, if you feel that it doesn't make sense for your workflow, and that any release is compatible, then I'll use the tag

**Comment by nijel** [comment]
Anyway the problem is that there is no 4.1 Docker image yet. It will be there hopefully shortly and the helm chart will be updated as well.
