### ISSUE TITLE
Confusing default values for SMTP (TLS/SSL)

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/helm#143]
### Describe the issue

The default values for SMTP are confusing:

https://github.com/WeblateOrg/helm/blob/c009d08912a252305ec0d3bb48ff6c9a468eb91c/charts/weblate/values.yaml#L33-L36

You can always only set one of these to true, otherwise celery complains: 
```
EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a helm release without setting either `emailTLS` or `emailSSL` to `false`
2. You won't be able to send emails with the exception below.

### Expected behavior

Since port 587 is used in the default values, I would suggest setting only `emailTLS` to `true`.

See also here:
https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-EMAIL_USE_TLS

### Exception traceback

```pytb
celery-notify stderr | [2022-02-28 15:31:11,160: ERROR/ForkPoolWorker-1] Failure while executing task
celery-notify stderr | Traceback (most recent call last):
celery-notify stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
celery-notify stderr |     R = retval = fun(*args, **kwargs)
celery-notify stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-notify stderr |     return self.run(*args, **kwargs)
celery-notify stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/accounts/tasks.py", line 138, in send_mails
celery-notify stderr |     connection = get_connection()
celery-notify stderr |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/__init__.py", line 35, in get_connection
celery-notify stderr |     return klass(fail_silently=fail_silently, **kwds)
celery-notify stderr |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 31, in __init__
celery-notify stderr |     raise ValueError(
celery-notify stderr | ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
```

**Comment by Mart-Kuc** [comment]
Fixed in this [PR](https://github.com/WeblateOrg/helm/pull/494)
