### ISSUE TITLE
Correctly set `settings-override.py` permissions

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/helm#16]
When creating the service with the helm chart, the following error is risen:

```
weblate.E027 	The path /app/data/settings-override.py is owned by different user, check your DATA_DIR settings.
```

I've seen that the file is mounted in the container with the following permissions:

```
-rw-r--r--  1 root    weblate     0 Jun 15 15:30 settings-override.py
```

While debugging this I've seen that the weblate user belongs to the root group though it doesn't have permissions to edit root owned files, wouldn't it be better if it didn't belong to that group?

```bash
weblate@weblate-547cf6f5b-pjwvz:/etc$ id
uid=1000(weblate) gid=1000(weblate) groups=1000(weblate),0(root),5(tty)
weblate@weblate-547cf6f5b-pjwvz:/etc$ echo "# hi" >> /etc/hosts
bash: hosts: Permission denied
```

**Comment by nijel** [comment]
It needs the root group, see https://github.com/WeblateOrg/docker/issues/326 and https://github.com/moby/moby/issues/31243#issuecomment-406879017

**Comment by nijel** [comment]
And it doesn't seem to be possible to set ownership correctly, see https://github.com/kubernetes/kubernetes/issues/2630

**Comment by br95187** [comment]
Same here.

I've just installed from chart and got this error:
`check stderr | CRITICALS:
check stderr | ?: (weblate.E027) The path /app/data/settings-override.py is owned by a different user, check your DATA_DIR settings.
check stderr | 	HINT: https://docs.weblate.org/en/weblate-4.5.1/admin/install.html#file-permissions
check stderr |`

/app/data owned by root and app is running on weblate user.

**Comment by nijel** [comment]
As mentioned before, this error is harmless. But it probably makes sense to exclude this particular file from the check...
