### ISSUE TITLE
Excessive Migration Time and Readiness/Liveness Timeouts During System Update

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/helm#320]
### Describe the issue

When performing an update, the migration process takes an excessive amount of time, leading to readiness/liveness timeouts and subsequent pod restarts.

The migration process exceeds the anticipated timeframe, resulting in readiness/liveness timeouts and the subsequent restart of the pod.

**The readiness and liveness timeouts are not adjustable via the values yaml file, which limits our ability to mitigate the issue.**

Recommendation: 
1. Introduce the option to modify the readiness and liveness timeout values as configurable variables in the values yaml file.
2. Alternatively, consider increasing the default readiness and liveness timeout values to accommodate scenarios where the migration process requires additional time due to limited hardware resources.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Initiate an update on the system.
2. Observe the migration process during the update.

### Expected behavior

The migration process completes within a reasonable timeframe, allowing the pod to maintain its readiness and liveness.

### Screenshots

![log](https://github.com/WeblateOrg/helm/assets/14855001/59426739-d22b-4f67-839b-d1cfce34a3ad)

### Additional context

https://github.com/WeblateOrg/helm/blob/5b01aced65f929b80afe055d9810de8e14b91bc7/charts/weblate/templates/deployment.yaml#L179-L192

The extended duration of the migration process on our system can be attributed to the constrained hardware resources available.

**Comment by nijel** [comment]
Some migrations can indeed take longer, at the container level, this has been addressed by https://github.com/WeblateOrg/docker/commit/e9baff1351e2062628f66d7c8d57fd30f78d8999, not sure whether this helps in Kubernetes as well.

**Comment by locomoco28** [comment]
Hi nijel, the `HEALTHCHECK` setting in Docker images is used for Docker to check if a container is running.

The `livenessProbe` and `readinessProbe` settings in Kubernetes deployments checks if the pod is running and if it's active to accept connections. You can rely solely on `HEALTHCHECK`, but you've got to remove liveness and readiness probes from the deployment in that case as otherwise they will kill the pod (or increase their configurations higher than the `HEALTHCHECK`).

**Comment by nijel** [comment]
I've increased the initialDelaySeconds to have same value as in https://github.com/WeblateOrg/docker/commit/e9baff1351e2062628f66d7c8d57fd30f78d8999.

Having a migration container would be probably a better approach, but that is way beyond my Kubernetes knowledge.
