### ISSUE TITLE
Pod takes too long to become ready

### ISSUE THREAD

**Issue by hnicke** [WeblateOrg/helm#325]
### Describe the issue

Lately the readiness probe [has been upped](https://github.com/WeblateOrg/helm/commit/0764e20b7c7dd553ca3d748609c73ae88fcf5956) to 300 seconds.
This is too high.
The chart is currently designed in a way that zero downtime deployments are not possible.
Therefore the startup time needs to improve.

In contrast to the liveness probe, a failing readiness probe is not a problem during container start up. I.e., kubernetes will not restart the container. A failing readiness probe will only exclude the container from being loadbalanced in the weblate service.

Both readiness probe initial delay and liveness probe initial delay should be configurable and use a sensible default value.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

deploy the app, app takes too until it's ready

**Comment by nijel** [comment]
The proper solution is probably to do the database migration in a separate step. There is really no sane value for the migrations time. It can be a few seconds when there is nothing to migrate, or hours in the case of some complex situations (like metrics rewrite a few releases ago).

**Comment by hnicke** [comment]
@nijel as outlined in #326 , it doesn't matter if the readiness probe fails due to the migration still running.
The deployment controller will simply  probe again. I.e., the pod will not get killed - that is only the case if the livenessProbe fails.
