### ISSUE TITLE
Cache not found

### ISSUE THREAD

**Issue by lanrekkeeg** [WeblateOrg/helm#418]
### Describe the issue

I am using Weblate with 2 replicas and a single volume (RWX). The volume is mounted on the default `/app/data`.

The cache folder is located at `/app/cache/static/`, and this folder is not part of the volume mount.

The problem is that I see 2 different cache files on each instance in `/app/cache/static/CACHE/css`. When a request is received randomly with a cache ID from a random instance, if it hits the right instance, it is fine. If not, it breaks the HTML page.

Shouldn't we mount `app` instead of `/app/data` so that the cache is available from both instances?

Replica one cache:

```
weblate@weblate-78f56f5d97-xz4hn:/app/cache/static/CACHE/css$ ls
output.5ceb8afe40df.css  output.dd5ad699a41d.css
```

Replica two cache:

```
weblate@weblate-78f56f5d97-ln4rh:/app/cache/static/CACHE/css$ ls
output.369cd91ac6fb.css  output.ca9306dee418.css
```

On replica one, this is the error message in the log when the request comes:

```
nginx stderr | 2024/03/05 10:21:50 [error] 267#267: *126612 open() "/app/cache/static/CACHE/css/output.369cd91ac6fb.css" failed (2: No such file or directory), client: 10.42.3.186, server: , request: "GET /static/CACHE/css/output.369cd91ac6fb.css HTTP/1.1", host: "----", referrer: "----"
```

If you see the error message, the cache file `output.369cd91ac6fb.css` is available on instance 2.

P.S. I am not sure how Weblate in the browser selects which cache to use and how this cache is generated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a Helm deployment with 2 replicas and a single volume mounted on /app/data.
2. Utilize external Redis and PostgreSQL.
3. Weblate version is 4.16.4-1.
4. PostgreSQL version is 15.
5. The rest of the configuration is default in the Helm chart.

**Comment by nijel** [comment]
Upgrade Weblate, this has been fixed some time ago: https://github.com/WeblateOrg/weblate/commit/b555de887ff620103f6492bc75b89eaae4f91a42
