### ISSUE TITLE
Readiness and Liveness probes

### ISSUE THREAD

**Issue by Mart-Kuc** [WeblateOrg/helm#468]
### Describe the issue

Hello,

Due to changes in this  [commit](https://github.com/WeblateOrg/helm/commit/f4ac69009b97ad806d6649721c50eec0d7aa7555) the values for the Readiness and Liveness probes are not being applied, and we are unable to set or override the new/default values.

Both probes still expect the values to be provided within a `with` statement as part of the code logic.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. `helm template -f values.yaml . > test.yaml`
Open `test.yaml` and values for `readiness` and `liveness` probes doesn't exist even they are bot defined in `values.yaml`
![Screenshot from 2024-09-17 13-24-54](https://github.com/user-attachments/assets/dcebc7d3-e037-48fa-82f4-ed2a07b19652)

### Expected behavior

We should see values which are defined in `values.yaml`
![Screenshot from 2024-09-17 13-26-01](https://github.com/user-attachments/assets/b65e953b-5da2-4052-8a29-a0474d3b0b93)

### Additional context

From my point of view this [PR](https://github.com/WeblateOrg/helm/pull/466) doesn't make sense. Because you replaced `with` statement with an `if` condition, but both serve the same purpose. If you have `if` condition or if you have `with` statement they both do same things. `with` statement will not be templated in case that you set empty bracket (`{}`) as  the value.

See example:
![Screenshot from 2024-09-17 13-31-24](https://github.com/user-attachments/assets/4c7ef924-1635-49dc-96d8-876a0f94ff1e)

So my suggestion is revert/remove this one [PR](https://github.com/WeblateOrg/helm/pull/466)

However, if you prefer to keep these changes, I have created a separate [PR](https://github.com/WeblateOrg/helm/pull/467) with the necessary fixes.

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/helm/pull/467, thanks.
