### ISSUE TITLE
Improve Artifact Hub presence

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/helm#469]
### Describe the problem

https://artifacthub.io/packages/helm/weblate/weblate should get "verified" and "official" checkmarks.

### Describe the solution you would like

The process is documented at https://artifacthub.io/docs/topics/repositories/#verified-publisher

### Additional context

I currently do not have access to the Artifact Hub organization and repository, so this needs to be figured out.

**Comment by nijel** [comment]
Ah, there is https://artifacthub.io/docs/topics/repositories/#ownership-claim.

**Comment by nijel** [comment]
@tarioch Do you happen to own Weblate repo and organization on Artifact Hub? If so, can you please add me there?

**Comment by tarioch** [comment]
Sent you the invite

**Comment by nijel** [comment]
Thanks, now I'm in the organization, but I still don't see the repo (even though it is in the organization). Can you please check if there is something else to give me permissions?

**Comment by nijel** [comment]
The verified badge is now there, and I've asked for the official badge in https://github.com/artifacthub/hub/issues/4045

**Comment by nijel** [comment]
The official badge is now there also.
