### ISSUE TITLE
common.tplvalues.render is not defined in _helpers.tpl

### ISSUE THREAD

**Issue by vokhmanov** [WeblateOrg/helm#502]
### Describe the issue

Hey guys,
I tried to add annotations to weblate service, but template of service.yaml is using common.tplvalues.render which is not defined anywhere.
I think you should add common.tplvalues.render to _helpers.tpl or change template service.yaml in the same way as ingress.yaml was defined.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. add annotations to service in values.yaml
2. helm template -f values.yaml . --debug
3. `Error: template: weblate/templates/service.yaml:8:19: executing "weblate/templates/service.yaml" at <include "common.tplvalues.render" (dict "value" $value "context" $)>: error calling include: template: no template "common.tplvalues.render" associated with template "gotpl"
helm.go:84: [debug] template: weblate/templates/service.yaml:8:19: executing "weblate/templates/service.yaml" at <include "common.tplvalues.render" (dict "value" $value "context" $)>: error calling include: template: no template "common.tplvalues.render" associated with template "gotpl"`

### Expected behavior

Annotations was added to service

**Comment by Mart-Kuc** [comment]
In case that you don't want to use bitnami upstream chart e.g `Postgres` and `redis` than it really doesn't work.

`common.tplvalues.render` is function included in Bitnami chart.

I am going to delete this one function because from our point of view it doesn't make sense to have it.

**Comment by Mart-Kuc** [comment]
Fixed in this [PR](https://github.com/WeblateOrg/helm/pull/505)
