### ISSUE TITLE
Getting a 502 when loading some pages on weblate

### ISSUE THREAD

**Issue by binte** [WeblateOrg/helm#74]
I am installing weblate with the following command:

`helm install weblate weblate/weblate -f path\to\values.yaml`

And the content of _values.yaml_ as follows:

```
adminEmail: "my.email@my.domain"
adminUser: "my.user"
adminPassword: "my.password"

service:
  type: LoadBalancer
```

All 3 pods are successfully created and running, but I keep getting 502 bad gateway for some actions on the page, namely every time I try to delete projects, and often when just trying to access the page. 

Any idea how I can fix this issue?

**Comment by nijel** [comment]
Check the logs, it will give you at least some insight.
