### ISSUE TITLE
Where to find the backup files for Weblate

### ISSUE THREAD

**Issue by raman030888** [WeblateOrg/helm#81]
Hi 

I want to know where we can find the automated backup files for weblate.
I have successfully deployed weblate via docker compose file and its working fine. We need to export the instance data and we cannot find the backup files. we were checking the path "/tmp/backups/" by connecting to the weblate container and its empty.
Can you help me in finding where the backup files stored. Attaching the screenshot for reference where we can see that the backups are successfully created.

Thanks In Advance!!

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/60535012/115405612-b4a60680-a1ee-11eb-861e-0d0bdd99e5ce.png)

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/backup.html#local-filesystem
