### ISSUE TITLE
Celery SIGKILL

### ISSUE THREAD

**Issue by sforner405** [WeblateOrg/helm#83]
Hi, 
we try to deploy weblate with the current helm charts, but the POD does not start correctly.
Right now we receive a lot of 502 and assume the problem is with celery, because we get a lot of SIGKILL log entries.

`2021-04-27 10:37:00,929 INFO success: celery-notify entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-27 10:37:00,929 INFO exited: celery-celery (terminated by SIGKILL; not expected)
2021-04-27 10:37:00,934 INFO spawned: 'celery-celery' with pid 29994
2021-04-27 10:37:01,363 INFO success: celery-translate entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-27 10:37:01,364 INFO exited: celery-memory (terminated by SIGKILL; not expected)
celery-beat stdout | celery beat v5.0.5 (singularity) is starting.`

`2021-04-27 10:36:55,925 INFO exited: celery-translate (terminated by SIGKILL; not expected)
celery-translate stderr | [2021-04-27 10:36:55,922: ERROR/ForkPoolWorker-1] Process ForkPoolWorker-1
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/process.py", line 327, in _bootstrap
celery-translate stderr |     self.run()
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/process.py", line 114, in run
celery-translate stderr |     self._target(*self._args, **self._kwargs)
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 290, in __call__
celery-translate stderr |     self.on_loop_start(pid=pid)  # callback on loop start
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/asynpool.py", line 240, in on_loop_start
celery-translate stderr |     self.outq.put((WORKER_UP, (pid,)))
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/queues.py", line 366, in put
celery-translate stderr |     self.send_payload(ForkingPickler.dumps(obj))
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/queues.py", line 358, in send_payload
celery-translate stderr |     self._writer.send_bytes(value)
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/connection.py", line 227, in send_bytes
celery-translate stderr |     self._send_bytes(m[offset:offset + size])
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/connection.py", line 453, in _send_bytes
celery-translate stderr |     self._send(header + buf)
celery-translate stderr |   File "/usr/local/lib/python3.7/dist-packages/billiard/connection.py", line 406, in _send
celery-translate stderr |     n = write(self._handle, buf)
celery-translate stderr | BrokenPipeError: [Errno 32] Broken pipe`

Anyone who has seen similar issues?

**Comment by nijel** [comment]
Maybe too many processes in the container? See https://docs.weblate.org/en/latest/admin/install/docker.html#number-of-processes-and-memory-consumption

**Comment by sforner405** [comment]
> Maybe too many processes in the container? See https://docs.weblate.org/en/latest/admin/install/docker.html#number-of-processes-and-memory-consumption

I could solve it.
The default resource limits for the pod had very low defaults. We had to raise the memory limits, so the oom killer does not take care of killing processes all the time.

@nijel Maybe it makes sense to add some default settings or recommended settings in the helm values yaml.

**Comment by nijel** [comment]
Right now the container defaults to spawn a number of processes depending on the number of CPU cores available. This doesn't work well for  environments like Kubernetes or OpenShift where the cluster might have a high number of CPU cores, but resources available to the pod are limited.
