### ISSUE TITLE
Authentication fails in clean weblate helm repo installation 

### ISSUE THREAD

**Issue by binte** [WeblateOrg/helm#84]
I am installing the latest weblate version on an AKS cluster, via the following command: 

`helm install weblate weblate/weblate -f C:\path\to\values.yaml
`

The content of values.yaml is as follows:

```
# adminEmail -- Email of Admin Account
adminEmail: "my-email@somecompany.com"
# adminUser -- Name of Admin Account
adminUser: "my-user"
# adminPassword -- Password of Admin Account
adminPassword: *********

service:
  type: LoadBalancer
```

Weblate goes in a crash loop after installation, and I am able to see this in the logs:

`psql: error: FATAL:  password authentication failed for user "postgres"`

What do you think is the issue here?

**Comment by nijel** [comment]
What is your configuration for postgresql.* settings?

**Comment by binte** [comment]
Hi @nijel 

I haven't changed anything in the chart repo, shouldn't running the installation command just work, out of the box?

**Comment by nijel** [comment]
It should.

Maybe the PostgreSQL password is not set because of the reasons described in the note here: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run

**Comment by binte** [comment]
I can't connect to the weblate container, because it's down, but when I connect to the database container, and echo the environment variables, I see that the user is 'postgres' and the password is 'weblate'. Which is aligned with what we see in the helm repo. 

So, which user and password should we actually use?

And how should we set it up when deploying the helm repo? The URL you sent me is for docker

**Comment by nijel** [comment]
The chart uses docker containers underneath.

**Comment by binte** [comment]
Alright, but what's the procedure to pass those parameters to the `helm install` command? 

I have tried to add the following to the values.yaml:

```
postgresqlUsername: "weblate" 

postgresqlPassword: "weblate"

postgresqlDatabase: "weblate"
```


(...) but I am still getting the same error

`psql: error: FATAL: password authentication failed for user "postgres"`


Trying to pass those values when invoking the command did not produce an error, but did not work either:

`helm install weblate weblate/weblate -f C:\path\to\values.yaml --set postgresqlUsername=weblate --set postgresqlPassword=weblate`


So, the values are not being picked up! Any idea how can I pass them?

**Comment by nijel** [comment]
> django.db.utils.ProgrammingError: permission denied for table django_migrations

The user does not have permission for the table. Most likely the `weblate` database is not owned by `weblate` user.

**Comment by binte** [comment]
I was able to fix this with a clean install of the cluster, before installing the helm chart. 

As the default policy of PVC claim is stateful set, deleting weblate via helm uninstall would not delete the database content.
