### ISSUE TITLE
Authentication with Azure AD 

### ISSUE THREAD

**Issue by raman030888** [WeblateOrg/helm#97]
Hi,
I have configured weblate with helm charts in AKS and trying to setup Authentication of weblate application with my Azure Active Directory. I had followed the steps provided in the documentation and got stuck in a place where we need to edit "weblate/settings.py"

I am not able to find the file "Weblate/settings.py" in my Weblate POD. Please help us with the path for "Weblate/settings.py"

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install/docker.html#ldap

**Comment by raman030888** [comment]
Hi,
The login page is not getting redirected to Azure login.
I have configured the settings as per the document and passed all the variables including Azure AD, Secret, key and tenant ID, verified the same in Container variables.

**Comment by nijel** [comment]
Ah, you mean Azure via OAuth, not by LDAP, then this is the correct docs: https://docs.weblate.org/en/latest/admin/install/docker.html#azure-active-directory

**Comment by nijel** [comment]
You might also want to disable e-mail/password based auth to get unconditional redirect to Azure, see https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_NO_EMAIL_AUTH

**Comment by raman030888** [comment]
Thanks the issue has been fixed.
